language: node_js
node_js:
  - '8'
deploy:
  skip_cleanup: true
script:
  - vue-cli-service build --dest public
deploy:
  provider: firebase
  token:
    secure: '1/J41_qUfTBhIklBdzORcqtov5iqR6aE3SXHfJ88fDVIY'
